#ifndef __org_universolibre_util_EasyDev_idl__
#define __org_universolibre_util_EasyDev_idl__

module org { module universolibre { module util { module EasyDev {

    interface XEasyDev
    {
        [attribute, readonly] string VERSION;
        [attribute, readonly] string OS;
        [attribute] string value;

        void debug([in] any data);
        void msgbox([in] any data);
        void mri([in] any obj);
        any cmd([in] string command, [in] any data);

        any newDoc([in] string typeDoc);
        any getDoc([in] string title);
        string getTypeDoc([in] any doc);
        sequence< any > getDocs();
        any openDoc([in] string pathDoc, [in] sequence< any > data);
        void setFocus([in] any doc);
        any getStatusBar([in] any doc);
        string exportPDF([in] any doc, [in] string pathSave, [in] sequence< any > options);

        any array([in] sequence< any > array, [in] string method, [in] any data);

        string getSizeScreen();
        sequence< string > getInfoPC();
        string getPath([in] string name);
        sequence< string > getPathInfo([in] string path);
        string pathJoin([in] sequence< string > paths);
        string getFolder([in] string initFolder);
        any getSelectedFiles([in] string initFolder, [in] boolean multiple, [in] sequence< string > filters);
        sequence< string > getFiles([in] string path, [in] string ext);
        any execute([in] sequence< string > args, [in] boolean wait);

        any getConfig([in] string key);
        boolean setConfig([in] string key, [in] any value);
        string getClipboard();
        void setClipboard([in] string text);

        boolean sendMail([in] sequence< sequence< any > > server, [in] sequence< sequence< string > > mail, [in] sequence< string > files);
        string render([in] string template, [in] sequence< sequence< any > > data);
        any fileOpen([in] string path, [in] string mode);
        string format([in] string template, [in] any data);

        boolean question([in] string title, [in] string message);
    };

    service EasyDev: XEasyDev;
}; }; }; };
#endif
